version: '2'
services:
  rabbitmq:
    environment:
      RABBITMQ_NODENAME: "rabbit"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    image: rabbitmq:3.7.8-management
    networks:
    - default
    ports:
    - "5672:5672"
  mysql:
    image: mysql:5.6.41
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./_dev/mysql:/var/lib/mysql:z
    networks:
      - default
    expose:
      - "3306"
    ports:
      - "3306:3306"
  wayne:
    image: 360cloud/wayne:latest
    depends_on:
      - rabbitmq
      - mysql
    command: /opt/wayne/backend apiserver
    environment:
      GOPATH: "/go"
    volumes:
      - ./src/backend/conf:/opt/wayne/conf:z
    networks:
      - default
    expose:
      - "8080"
    ports:
      - "8080:8080"
