INSERT INTO  permission  ( id,  name,  comment,  create_time,  update_time ) VALUES ('122', 'INGRESS_CREATE', '', now(), now());
INSERT INTO  permission  ( id,  name,  comment,  create_time,  update_time ) VALUES ('123', 'INGRESS_UPDATE', '', now(), now());
INSERT INTO  permission  ( id,  name,  comment,  create_time,  update_time ) VALUES ('124', 'INGRESS_READ', '', now(), now());
INSERT INTO  permission  ( id,  name,  comment,  create_time,  update_time ) VALUES ('125', 'INGRESS_DELETE', '', now(), now());
INSERT INTO  permission  ( id,  name,  comment,  create_time,  update_time ) VALUES ('126', 'INGRESS_DEPLOY', '', now(), now());

INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3876', '10', '95');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3877', '10', '96');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3878', '10', '97');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3879', '10', '98');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3880', '10', '99');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3881', '10', '100');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3882', '10', '101');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3883', '10', '102');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3884', '10', '103');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3885', '10', '122');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3886', '10', '123');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3887', '10', '124');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3888', '10', '125');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('3889', '10', '126');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('1905', '11', '96');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('1906', '11', '97');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('1907', '11', '99');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('1908', '11', '100');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('1909', '11', '123');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('1910', '11', '124');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('1911', '11', '126');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('2917', '12', '124');
INSERT INTO  group_permissions  ( id,  group_id,  permission_id ) VALUES ('2918', '12', '126');
